# Using numpy lib for ops over arrays, powerful tool of python.


In [1]:
a = [0,0,1,4,7,16,31,64,127]
import numpy as np
b = np.array(a)

In [2]:
b

array([  0,   0,   1,   4,   7,  16,  31,  64, 127])

In [3]:
c = np.array([1, 4., -2, 7])

In [4]:
c

array([ 1.,  4., -2.,  7.])

In [5]:
np.linspace(0, 45, 5)

array([ 0.  , 11.25, 22.5 , 33.75, 45.  ])

In [6]:
np.logspace(1, 3, 5)

array([  10.        ,   31.6227766 ,  100.        ,  316.22776602,
       1000.        ])