
# Math ops with arrays, transform all the elements of array in one fell swoop.

In [1]:
import numpy as np
a = np.linspace(-1., 5, 7)
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [2]:
a*6

array([-6.,  0.,  6., 12., 18., 24., 30.])

In [3]:
a/5

array([-0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [4]:
a**3

array([ -1.,   0.,   1.,   8.,  27.,  64., 125.])

In [5]:
a+4

array([3., 4., 5., 6., 7., 8., 9.])

In [6]:
a-10

array([-11., -10.,  -9.,  -8.,  -7.,  -6.,  -5.])

In [7]:
(a+3)*2

array([ 4.,  6.,  8., 10., 12., 14., 16.])

In [8]:
np.sin(a)

array([-0.84147098,  0.        ,  0.84147098,  0.90929743,  0.14112001,
       -0.7568025 , -0.95892427])

In [9]:
%precision 4
np.sin(a)

array([-0.8415,  0.    ,  0.8415,  0.9093,  0.1411, -0.7568, -0.9589])