In [1]:
import numpy as np
a = np.linspace(-1., 5, 7)
a

array([-1.,  0.,  1.,  2.,  3.,  4.,  5.])

In [2]:
np.exp(-a)

array([2.71828183, 1.        , 0.36787944, 0.13533528, 0.04978707,
       0.01831564, 0.00673795])

# %precision 4


In [5]:
np.exp(-a)

array([2.7183, 1.    , 0.3679, 0.1353, 0.0498, 0.0183, 0.0067])

In [6]:
1. + np.exp(-a)

array([3.7183, 2.    , 1.3679, 1.1353, 1.0498, 1.0183, 1.0067])

In [7]:
b = 5*np.ones(8)

In [8]:
b

array([5., 5., 5., 5., 5., 5., 5., 5.])

In [9]:
b+=4

In [10]:
b

array([9., 9., 9., 9., 9., 9., 9., 9.])

#Even fairly complex algebraic computations can be carried out this way. 